-- ============================================================
-- SQL SCHEMA FOR SUPABASE DATABASE (Order & Invoice Tracker)
-- ============================================================

-- 1. Create table 'orders'
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(100) NOT NULL,
    invoice_no VARCHAR(100) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    order_date DATE DEFAULT CURRENT_DATE,
    amount NUMERIC(15, 2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create index for faster searching
CREATE INDEX IF NOT EXISTS idx_orders_order_no ON public.orders(order_no);
CREATE INDEX IF NOT EXISTS idx_orders_invoice_no ON public.orders(invoice_no);
CREATE INDEX IF NOT EXISTS idx_orders_customer_name ON public.orders(customer_name);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policy (Allow public read, insert, update, delete for simple access)
CREATE POLICY "Allow public full access to orders"
ON public.orders
FOR ALL
USING (true)
WITH CHECK (true);

-- 5. Insert initial seed data
INSERT INTO public.orders (order_no, invoice_no, customer_name, order_date, amount, status, notes)
VALUES 
    ('ORD-2026-001', 'INV-2026-001', 'PT Maju Bersama', '2026-09-01', 15500000, 'Lunas', 'Pembayaran via BCA Transfer'),
    ('ORD-2026-002', 'INV-2026-002', 'Toko Sumber Rejeki', '2026-09-04', 8200000, 'Dikirim', 'Resi JNE: 8829103948'),
    ('ORD-2026-003', 'INV-2026-003', 'CV Karya Utama', '2026-09-07', 24000000, 'Diproses', 'Menunggu konfirmasi gudang'),
    ('ORD-2026-004', 'INV-2026-004', 'Budi Santoso', '2026-09-08', 3500000, 'Pending', 'Tagihan telah dikirim ke WA')
ON CONFLICT DO NOTHING;
