-- ============================================================
-- SQL SCHEMA FOR SUPABASE DATABASE (Order & Invoice Tracker)
-- ============================================================

-- 1. Create table 'orders'
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity VARCHAR(100),
    business_unit VARCHAR(100),
    jenis_transaksi VARCHAR(100),
    nama_pelanggan VARCHAR(255),
    no_invoice VARCHAR(100),
    order_date DATE,
    accounting_date DATE,
    nama_kategori VARCHAR(100),
    principal VARCHAR(255),
    brand VARCHAR(100),
    order_number VARCHAR(100),
    item_code VARCHAR(100),
    item_description TEXT,
    qty NUMERIC(15, 2) DEFAULT 0,
    uom VARCHAR(50),
    lot_number VARCHAR(100),
    hna NUMERIC(15, 2) DEFAULT 0,
    diskon_pct NUMERIC(8, 2) DEFAULT 0,
    diskon_principal NUMERIC(8, 2) DEFAULT 0,
    diskon_principal_rp NUMERIC(15, 2) DEFAULT 0,
    diskon_distribution NUMERIC(8, 2) DEFAULT 0,
    diskon_distribution_rp NUMERIC(15, 2) DEFAULT 0,
    harga_jual NUMERIC(15, 2) DEFAULT 0,
    total_harga NUMERIC(15, 2) DEFAULT 0,
    cugs_unit NUMERIC(15, 2) DEFAULT 0,
    cugs_total NUMERIC(15, 2) DEFAULT 0,
    profit NUMERIC(15, 2) DEFAULT 0,
    kota_alamat VARCHAR(150),
    masa_jatuh_tempo VARCHAR(100),
    status_print VARCHAR(50) DEFAULT 'Belum Diprint',
    status VARCHAR(50) DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create indexes for fast search
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON public.orders(order_number);
CREATE INDEX IF NOT EXISTS idx_orders_no_invoice ON public.orders(no_invoice);
CREATE INDEX IF NOT EXISTS idx_orders_nama_pelanggan ON public.orders(nama_pelanggan);
CREATE INDEX IF NOT EXISTS idx_orders_status_print ON public.orders(status_print);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policy
CREATE POLICY "Allow public full access to orders"
ON public.orders FOR ALL USING (true) WITH CHECK (true);

-- 5. Sample seed data matching Excel structure
INSERT INTO public.orders (
    entity, business_unit, jenis_transaksi, nama_pelanggan, no_invoice, 
    order_date, accounting_date, nama_kategori, principal, order_number, 
    item_code, item_description, qty, uom, lot_number, 
    diskon_pct, diskon_distribution_rp, total_harga, kota_alamat, masa_jatuh_tempo, status_print, status
)
VALUES 
    ('MBI', 'MBI Business Unit', 'TRADE_3RD PARTY', 'PT Guna Nalar Insan', '71', '2026-09-07', '2026-09-01', 'PPIC Regular', 'PPIC Soho Industri Pharmasi', 'KY74DY-8596', '17490', 'IMBOOST 5 CATCH COVER @ 4 TABLET -', 50, 'BOX', '26S0103', 3, 2208000, 2208000, 'Denpasar', '20', 'Belum Diprint', 'Pending'),
    ('MBI', 'MBI Business Unit', 'TRADE_3RD PARTY', 'Apotek Gama 2', '70', '2026-09-07', '2026-09-01', 'PPIC Regular', 'PPIC Cendo Pharmaceutical', 'ZLGMXL-8003', '9241', 'CENDO LYTEERS EYE DROPS 15ML - CENDO', 30, 'BTL', '6L01062', 13.5, 3189375, 3189375, 'Cilegon', '20', 'Belum Diprint', 'Diproses'),
    ('MBI', 'MBI Business Unit', 'TRADE_3RD PARTY', 'Apotek Gama 2', '70', '2026-09-07', '2026-09-01', 'PPIC Regular', 'PPIC Eagle Indo Pharma', 'ZLGMXL-8003', '9658', 'CAP LANG MINYAK KAYU PUTIH 60 ML - EAGLE INDO PHARMA', 100, 'BTL', 'HC01216', 0.5, 9548500, 9548500, 'Cilegon', '20', 'Sudah Diprint', 'Selesai')
ON CONFLICT DO NOTHING;
